#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-LCDproc
version:      0.031
version_from: LCDproc.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
